name: Daily Content Management

on:
  schedule:
    - cron: '0 6 * * *' # 9 AM Moscow time (UTC+3)
  workflow_dispatch: # Allow manual triggering from GitHub Actions UI
  repository_dispatch:
    types: [daily-content-trigger]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  content-management:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITBOT_GITHUB_TOKEN }}
      
      - name: Run content management
        run: |
          bash scripts/run-content-management.sh
      
      - name: Commit and push changes
        run: |
          git config --local user.email "gitbot@outspy.com"
          git config --local user.name "Content Manager"
          git add .
          git diff --staged --quiet || git commit -m "Daily content management - $(date +%Y-%m-%d)"
          git push

